### ISSUE TITLE
Startup with MULTI_TREE is broken in New Search

### ISSUE THREAD

**Issue by genofire** [gramps-project/gramps-web-api#531] opened 2024-08-07 07:42 UTC
Container (ghcr.io/gramps-project/grampsweb:v24.7.1) startup Problem:
```
ls: cannot access '/app/indexdir/*.db': No such file or directory
/usr/local/lib/python3.11/dist-packages/gramps/plugins/tool/check.py:51: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk

(__main__.py:9): Gtk-CRITICAL **: 07:41:32.293: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 230, in <module>
    cli(
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 128, in search
    raise ValueError("`tree` is required when multi-tree support is enabled.")
ValueError: `tree` is required when multi-tree support is enabled.

```

**Comment by DavidMStraub** [comment] 2024-08-07 08:04
That has nothing to do with the new search backend. The problem is that the default entrypoint is not compatible with the multi-tree setup. That issue is already tracked in https://github.com/gramps-project/gramps-web-api/issues/510. Closing as duplicate.

**Closed by DavidMStraub** 2024-08-07 08:04 UTC
