### ISSUE TITLE
Gramps Web API waste DB connections (Postgres)

### ISSUE THREAD

**Issue by Illia-M** [gramps-project/gramps-web-api#562] opened 2024-10-27 07:30 UTC
I have a tree with 31k+ persons, a lot of other entities including media. When I walk in lists and try do some things on site - it lead to hang, next I get 500 error pop-ups and next in logout me and I can not login. After investigation I see that connections to Postgres reach default limit of 100 and not free up connections. CPU load is minimal, RAM almost full after it happens. Usually only reboot or docker-compose down-up helps.

![Screenshot 2024-10-27 о 09 23 54](https://github.com/user-attachments/assets/eda1dd36-a235-4cb3-935b-770cedac454b)

DigitalOcean Droplet, 4 vCPU 8 GB RAM

Postgres image from docs(15.8).

Gramps 5.2.2
Gramps Web API 2.4.2
Gramps Web Frontend 24.8.0
Gramps QL 0.3.0
locale: en
multi-tree: false
task queue: true

**Comment by Illia-M** [comment] 2024-10-27 07:32
![Знімок екрана 2024-10-27 о 09 32 37](https://github.com/user-attachments/assets/441ee7dd-12d1-4b0d-8441-dc0805bcfbc6)
![Знімок екрана 2024-10-27 о 09 32 28](https://github.com/user-attachments/assets/4b982c8e-fe30-42a5-b405-98d3ac524c2e)
![Знімок екрана 2024-10-27 о 09 32 19](https://github.com/user-attachments/assets/9066fb48-7b3e-44a6-a8a5-34a13b576ff1)

**Comment by Illia-M** [comment] 2024-10-27 07:48
![image](https://github.com/user-attachments/assets/18a3b600-eea7-4b92-8ed0-2a3f6d00ec78)

**Comment by DavidMStraub** [comment] 2024-10-27 08:16
Correct, but this was fixed in v2.4.3: https://github.com/gramps-project/gramps-web-api/releases/tag/v2.4.3

**Comment by DavidMStraub** [comment] 2024-10-27 08:17
(Duplicate of https://github.com/gramps-project/gramps-web-api/issues/552)

**Closed by DavidMStraub** 2024-10-27 08:16 UTC
