### ISSUE TITLE
Fan chart doesn't work

### ISSUE THREAD

**Issue by hcscherzer609** [gramps-project/gramps-web-api#537] opened 2024-08-21 13:55 UTC
I tried the demo family on gramshub and did not succeed to get the fan chart work

**Comment by DavidMStraub** [comment] 2024-08-21 15:42
Hi,

since it works for me, it must be a browser or frontend issue.

![grafik](https://github.com/user-attachments/assets/b1d86de2-5a98-4202-9b3f-9b5ba72531da)

Are you using Safari? Then it's a duplicate of https://github.com/gramps-project/gramps-web/issues/452.

**Comment by hcscherzer609** [comment] 2024-08-21 15:45
Yes, it's a Safari problem.
Chrome and Firefox: OK

**Closed** 2024-08-21 15:46 UTC
Labels: question

**Comment by DavidMStraub** [comment] 2024-08-21 15:47
Thanks for confirming.
