### ISSUE TITLE
smtp after initial web-setup not working

### ISSUE THREAD

**Issue by Shablone** [gramps-project/gramps-web-api#485] opened 2024-02-04 18:41 UTC
Hi

I've setup this docker compose 

```
version: "3.7"

services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: unless-stopped
    networks:
      - myserver_core_net_nginx
      - net_gramps
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      VIRTUAL_PORT: "5000"
      VIRTUAL_HOST: "grampsweb"  # e.g. gramps.mydomain.com
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
      GUNICORN_NUM_WORKERS: 2

      
    depends_on:
      - grampsweb_redis
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files
      - gramps_tmp:/tmp
    labels:
      - com.centurylinklabs.watchtower.enable=true

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO
    networks:
      - net_gramps
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  grampsweb_redis:
    image: redis:alpine
    container_name: grampsweb_redis
    restart: unless-stopped
    networks:
      - net_gramps
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
  gramps_tmp:

networks:
  myserver_core_net_nginx:
    external: true
  net_gramps:
```

After ramping it up, I browsed it and could set up my first user and I also filled the fields for the mailings.
![209728153-3fdda55f-fe5d-44e3-b861-0f69426ac07d](https://github.com/gramps-project/gramps-web-api/assets/20610621/fd7cd9c2-31be-440d-b20a-4ce64a136780)

I didn't execute any other commands or fill any environment variable.

When I register for a new account, no mails will be sent.

docker has no logs regarding this.
I don't know where this is configuration is saved, but there is no config file and no environment variable present in my grampsweb container

```
docker compose exec grampsweb /bin/bash
root@3b88d5a6f12f:/app# export
declare -x DEBIAN_FRONTEND="noninteractive"
declare -x GRAMPSWEB_CELERY_CONFIG__broker_url="redis://grampsweb_redis:6379/0"
declare -x GRAMPSWEB_CELERY_CONFIG__result_backend="redis://grampsweb_redis:6379/0"
declare -x GRAMPSWEB_EXPORT_DIR="/app/cache/export"
declare -x GRAMPSWEB_MEDIA_BASE_DIR="/app/media"
declare -x GRAMPSWEB_RATELIMIT_STORAGE_URI="redis://grampsweb_redis:6379/1"
declare -x GRAMPSWEB_REPORT_DIR="/app/cache/reports"
declare -x GRAMPSWEB_SEARCH_INDEX_DIR="/app/indexdir"
declare -x GRAMPSWEB_STATIC_PATH="/app/static"
declare -x GRAMPSWEB_THUMBNAIL_CACHE_CONFIG__CACHE_DIR="/app/thumbnail_cache"
declare -x GRAMPSWEB_TREE="Gramps Web"
declare -x GRAMPSWEB_USER_DB_URI="sqlite:////app/users/users.sqlite"
declare -x GRAMPS_API_CONFIG="/app/config/config.cfg"
declare -x GRAMPS_VERSION="51"
declare -x GUNICORN_NUM_WORKERS="2"
declare -x HOME="/root"
declare -x HOSTNAME="3b88d5a6f12f"
declare -x LANG="en_US.utf8"
declare -x LANGUAGE="en_US.utf8"
declare -x LC_ALL="en_US.utf8"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PWD="/app"
declare -x PYTHONPATH=":/usr/lib/python3/dist-packages"
declare -x SHLVL="1"
declare -x TERM="xterm"
declare -x VIRTUAL_HOST="grampsweb"
declare -x VIRTUAL_PORT="5000"
root@3b88d5a6f12f:/app# cat config/config.cfg
root@3b88d5a6f12f:/app#


```

**Comment by DavidMStraub** [comment] 2024-02-04 19:32
Please use the search function before opening issues.

Closing as duplicate of #325.

**Closed by DavidMStraub** 2024-02-04 19:32 UTC

**Comment by Shablone** [comment] 2024-02-04 19:34
I did
And #325 is a completly different matter. There the problem is a not updatening configuration if environment variables are set.
Here I have not environment variables

**Comment by DavidMStraub** [comment] 2024-02-04 20:55
Hi,

sorry if I misunderstood your issue.

It is kind of related as it would be easier for you if it were possible to modify the database-stored e-mail configuration later on, which is currently not possible, only by calling the API directly. When you use this form, the configuration is stored in the database.

You can also ignore the form and just use environment variables/config files.

I still believe it was correct closing this issue as improved handling of database-stored e-mail config is tracked in #325, and everything else is just setup issues. Bad please weigh in if you think there is a separate issue (with Gramps Web API - not your configuration).

**Comment by DavidMStraub** [comment] 2025-09-14 18:41
SMTP without TLS is only possible on port 25 right now because I didn't think anybody would/should be using this in production.

https://github.com/gramps-project/gramps-web-api/blob/393e5d6d6ffda4935ec901860f3c6ff9b5f68af0/gramps_webapi/api/util.py#L544-L551

**Comment by DavidMStraub** [comment] 2025-09-14 19:16
Sorry, not sure how to debug on my end. Let's please not use this issue thread to debug your setup.

**Comment by BFroberg** [comment] 2025-09-14 19:19
That's fair, I just figured it might be related if the db carries over my initial setup and the variables can't overrule it is all. Didn't want to open excessive topics. 
But you see no issues with my variables, then?
